name: pearsonuxcommittee
favicon: null
layout_spectrum: 0.7737345034256577
typography_spectrum: 0.3778906299266964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.45978635223582387
  lightness: 0.8982697036117315
  saturation: 0.9283319253008813
  rhythmicContrast: 0.027421574341133237
purpose: []
