analytics: {}
color:
  brandColors:
    - '#d4ebe5'
    - '#0080a7'
    - '#3b3630'
    - '#7b817b'
    - '#9ba8a2'
  brandStrength: 0.336622
  lightness: 0
  rhythmicContrast: 0.25
  saturation: 0.462719
cta: {}
layout_spectrum: 0
name: pearsonuxcommittee
opengraph: {}
purpose: []
typography_spectrum: 0.3778906299266964
