layout_spectrum: 0.2132116
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.6331901
  lightness: 0
  brandColors:
    - '#d4ebe5'
    - '#0080a7'
    - '#3b3630'
    - '#7b817b'
    - '#9ba8a2'
  rhythmicContrast: 0.25
typography_spectrum: 0.3778906299266964
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: pearsonuxcommittee
