name: pearsonuxcommittee
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3778906299266964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4ebe5'
    - '#0080a7'
    - '#3b3630'
    - '#7b817b'
    - '#9ba8a2'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
