analytics: {}
color:
  brandColors:
    - '#d4ebe5'
    - '#0080a7'
    - '#3b3630'
    - '#7b817b'
    - '#9ba8a2'
  brandStrength: 0.6331901
  lightness: 0
  rhythmicContrast: 0.25
  saturation: 1
cta: {}
layout_spectrum: 0.221491
name: pearsonuxcommittee
opengraph: {}
purpose: []
typography_spectrum: 0.3778906299266964
